services:
  - type: web
    name: website-doc-generator
    env: docker
    dockerfilePath: Dockerfile
    branch: main  # your GitHub branch
    envVars:
      - key: GOOGLE_API_KEY
        fromDatabase: false
      - key: PORT
        value: 10000
    plan: free
